module.exports = {
    testcases: [
        { input: [5, 14], expected: 3, isPublic: true, description: '5 animals and 14 legs gives 3 chickens' },
        { input: [10, 28], expected: 6, isPublic: true, description: '10 animals and 28 legs gives 6 chickens' },
        { input: [4, 8], expected: 4, isPublic: true, description: 'All chickens case: 4 animals and 8 legs' },
        { input: [4, 16], expected: 0, isPublic: false, description: 'All cows case: 4 animals and 16 legs' },
        { input: [1, 2], expected: 1, isPublic: false, description: 'Single chicken case' },
        { input: [1, 4], expected: 0, isPublic: false, description: 'Single cow case' },
        { input: [0, 0], expected: 0, isPublic: false, description: 'Zero animals and zero legs gives zero chickens' },
        { input: [2, 6], expected: 1, isPublic: false, description: '2 animals and 6 legs gives 1 chicken' },
        { input: [8, 20], expected: 6, isPublic: false, description: '8 animals and 20 legs gives 6 chickens' },
        { input: [8, 32], expected: 0, isPublic: false, description: '8 animals and 32 legs means all cows' },
        { input: [8, 16], expected: 8, isPublic: false, description: '8 animals and 16 legs means all chickens' },
        { input: [3, 10], expected: 1, isPublic: false, description: '3 animals and 10 legs gives 1 chicken' },
        { input: [3, 8], expected: 2, isPublic: false, description: '3 animals and 8 legs gives 2 chickens' },
        { input: [6, 18], expected: 3, isPublic: false, description: '6 animals and 18 legs gives 3 chickens' },
        { input: [6, 22], expected: 1, isPublic: false, description: '6 animals and 22 legs gives 1 chicken' },
        { input: [7, 24], expected: 2, isPublic: false, description: '7 animals and 24 legs gives 2 chickens' },
        { input: [5, 12], expected: 4, isPublic: false, description: '5 animals and 12 legs gives 4 chickens' },
        { input: [5, 20], expected: 0, isPublic: false, description: '5 animals and 20 legs means all cows' },
        { input: [5, 10], expected: 5, isPublic: false, description: '5 animals and 10 legs gives 5 chickens' },
        {
            input: [2, 8],
            expected: 0,
            isPublic: false,
            description: '2 animals and 8 legs means all cows',
        },
    ],
};
