module.exports = {
    testcases: [
        {
            input: [{ '1st': 'Alice', '2nd': 'Bob', '3rd': 'Charlie' }],
            expected: 'Alice',
            isPublic: true,
            description: 'Returns first winner from standard podium object',
        },
        {
            input: [{ '1st': 'Team Red', '2nd': 'Team Blue' }],
            expected: 'Team Red',
            isPublic: true,
            description: 'Returns first place when only top two ranks are present',
        },
        {
            input: [{ '1st': '' }],
            expected: '',
            isPublic: true,
            description: 'Returns empty string when first winner is empty',
        },
        {
            input: [{ '1st': 'Winner One', event: 'Sprint' }],
            expected: 'Winner One',
            isPublic: false,
            description: 'Ignores unrelated properties and returns 1st value',
        },
        {
            input: [{ '1st': 'Alice A.', '2nd': 'Bob B.' }],
            expected: 'Alice A.',
            isPublic: false,
            description: 'Returns string winner name with period correctly',
        },
        {
            input: [{ '1st': 'Bob-Junior', '2nd': 'Cara' }],
            expected: 'Bob-Junior',
            isPublic: false,
            description: 'Returns hyphenated first winner name correctly',
        },
        {
            input: [{ '1st': 'Zoe 1', '2nd': 'Nia 2' }],
            expected: 'Zoe 1',
            isPublic: false,
            description: 'Returns name containing a number as a string',
        },
        {
            input: [{ '1st': 'First Place', '2nd': 'Second Place' }],
            expected: 'First Place',
            isPublic: false,
            description: 'Returns phrase value from the 1st property',
        },
        {
            input: [{ '1st': 'Champion' }],
            expected: 'Champion',
            isPublic: false,
            description: 'Returns single-word winner name correctly',
        },
        {
            input: [{ '1st': 'Nora', '2nd': 'Oli', '3rd': 'Pam' }],
            expected: 'Nora',
            isPublic: false,
            description: 'Returns standard winner name correctly',
        },
        {
            input: [{ '1st': 'Kai', '2nd': 'Leo' }],
            expected: 'Kai',
            isPublic: false,
            description: 'Returns short string winner name correctly',
        },
        {
            input: [{ '1st': 'Mia', '2nd': 'Noah' }],
            expected: 'Mia',
            isPublic: false,
            description: 'Returns first winner when both top ranks are strings',
        },
        {
            input: [{ '1st': 'A', '1ST': 'B' }],
            expected: 'A',
            isPublic: false,
            description: 'Uses exact case-sensitive key 1st',
        },
        {
            input: [{ first: 'Alice', '1st': 'Zoe' }],
            expected: 'Zoe',
            isPublic: false,
            description: 'Returns literal 1st key instead of similarly named keys',
        },
        {
            input: [{ '1st': '  Alice  ', '2nd': 'Bob' }],
            expected: '  Alice  ',
            isPublic: false,
            description: 'Preserves whitespace in the returned first winner string',
        },
        {
            input: [{ '1st': 'A'.repeat(30), '2nd': 'B' }],
            expected: 'A'.repeat(30),
            isPublic: false,
            description: 'Handles long first winner strings correctly',
        },
        {
            input: [{ '1st': 'A/B Test Winner', '2nd': 'Runner Up' }],
            expected: 'A/B Test Winner',
            isPublic: false,
            description: 'Handles slash character in winner name string',
        },
        {
            input: [{ '1st': "O'Connor", '2nd': 'Lee' }],
            expected: "O'Connor",
            isPublic: false,
            description: 'Handles apostrophe in winner name string',
        },
        {
            input: [{ '1st': 'Champion Open', rank: 1, category: 'Open' }],
            expected: 'Champion Open',
            isPublic: false,
            description: 'Works with additional metadata fields in the object',
        },
        {
            input: [{ rank1: 'Wrong', '1st': 'Correct', '2nd': 'Runner-up' }],
            expected: 'Correct',
            isPublic: false,
            description: 'Selects the exact 1st property among similar keys',
        },
    ],
};
