module.exports = {
    testcases: [
        { input: [16], expected: 4, isPublic: true, description: '16 can be divided by 2 exactly 4 times' },
        { input: [10], expected: 1, isPublic: true, description: '10 can be divided by 2 once before becoming odd' },
        { input: [1], expected: 0, isPublic: true, description: '1 is odd so no divisions by 2' },
        { input: [2], expected: 1, isPublic: false, description: '2 can be divided by 2 once' },
        { input: [8], expected: 3, isPublic: false, description: '8 -> 4 -> 2 -> 1 gives 3 divisions' },
        { input: [12], expected: 2, isPublic: false, description: '12 -> 6 -> 3 gives 2 divisions' },
        { input: [18], expected: 1, isPublic: false, description: '18 -> 9 gives 1 division' },
        { input: [64], expected: 6, isPublic: false, description: '64 is 2^6 so answer is 6' },
        { input: [1024], expected: 10, isPublic: false, description: '1024 is 2^10 so answer is 10' },
        { input: [0], expected: 0, isPublic: false, description: '0 is treated as no valid finite repeated divisions' },
        { input: [-2], expected: 1, isPublic: false, description: '-2 -> -1 gives 1 division' },
        { input: [-8], expected: 3, isPublic: false, description: '-8 -> -4 -> -2 -> -1 gives 3 divisions' },
        { input: [3], expected: 0, isPublic: false, description: 'Odd number 3 gives 0 divisions' },
        { input: [25], expected: 0, isPublic: false, description: 'Odd number 25 gives 0 divisions' },
        { input: [40], expected: 3, isPublic: false, description: '40 -> 20 -> 10 -> 5 gives 3 divisions' },
        { input: [48], expected: 4, isPublic: false, description: '48 -> 24 -> 12 -> 6 -> 3 gives 4 divisions' },
        { input: [7], expected: 0, isPublic: false, description: 'Odd number 7 gives 0 divisions' },
        { input: [96], expected: 5, isPublic: false, description: '96 -> 48 -> 24 -> 12 -> 6 -> 3 gives 5 divisions' },
        { input: [81], expected: 0, isPublic: false, description: 'Odd number 81 gives 0 divisions' },
        { input: [-1], expected: 0, isPublic: false, description: 'Odd negative -1 gives 0 divisions' },
    ],
};
