const typeChart = {
    normal: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 0.5,
        ghost: 0,
        dragon: 1,
        dark: 1,
        steel: 0.5,
        fairy: 1,
    },
    fire: {
        normal: 1,
        fire: 0.5,
        water: 0.5,
        electric: 1,
        grass: 2,
        ice: 2,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 2,
        rock: 0.5,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 2,
        fairy: 1,
    },
    water: {
        normal: 1,
        fire: 2,
        water: 0.5,
        electric: 1,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 2,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 2,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 1,
        fairy: 1,
    },
    electric: {
        normal: 1,
        fire: 1,
        water: 2,
        electric: 0.5,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 0,
        flying: 2,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 1,
        fairy: 1,
    },
    grass: {
        normal: 1,
        fire: 0.5,
        water: 2,
        electric: 1,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 0.5,
        ground: 2,
        flying: 0.5,
        psychic: 1,
        bug: 0.5,
        rock: 2,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 0.5,
        fairy: 1,
    },
    ice: {
        normal: 1,
        fire: 0.5,
        water: 0.5,
        electric: 1,
        grass: 2,
        ice: 0.5,
        fighting: 1,
        poison: 1,
        ground: 2,
        flying: 2,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 1,
        steel: 0.5,
        fairy: 1,
    },
    fighting: {
        normal: 2,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 2,
        fighting: 1,
        poison: 0.5,
        ground: 1,
        flying: 0.5,
        psychic: 0.5,
        bug: 0.5,
        rock: 2,
        ghost: 0,
        dragon: 1,
        dark: 2,
        steel: 2,
        fairy: 0.5,
    },
    poison: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 2,
        ice: 1,
        fighting: 1,
        poison: 0.5,
        ground: 0.5,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 0.5,
        ghost: 0.5,
        dragon: 1,
        dark: 1,
        steel: 0,
        fairy: 2,
    },
    ground: {
        normal: 1,
        fire: 2,
        water: 1,
        electric: 2,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 2,
        ground: 1,
        flying: 0,
        psychic: 1,
        bug: 0.5,
        rock: 2,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 2,
        fairy: 1,
    },
    flying: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 0.5,
        grass: 2,
        ice: 1,
        fighting: 2,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 2,
        rock: 0.5,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 0.5,
        fairy: 1,
    },
    psychic: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 2,
        poison: 2,
        ground: 1,
        flying: 1,
        psychic: 0.5,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 1,
        dark: 0,
        steel: 0.5,
        fairy: 1,
    },
    bug: {
        normal: 1,
        fire: 0.5,
        water: 1,
        electric: 1,
        grass: 2,
        ice: 1,
        fighting: 0.5,
        poison: 0.5,
        ground: 1,
        flying: 0.5,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 0.5,
        dragon: 1,
        dark: 2,
        steel: 0.5,
        fairy: 0.5,
    },
    rock: {
        normal: 1,
        fire: 2,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 2,
        fighting: 0.5,
        poison: 1,
        ground: 0.5,
        flying: 2,
        psychic: 1,
        bug: 2,
        rock: 1,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 0.5,
        fairy: 1,
    },
    ghost: {
        normal: 0,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 2,
        dragon: 1,
        dark: 0.5,
        steel: 1,
        fairy: 1,
    },
    dragon: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 1,
        steel: 0.5,
        fairy: 0,
    },
    dark: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 0.5,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 2,
        dragon: 1,
        dark: 0.5,
        steel: 1,
        fairy: 0.5,
    },
    steel: {
        normal: 1,
        fire: 0.5,
        water: 0.5,
        electric: 0.5,
        grass: 1,
        ice: 2,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 2,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 0.5,
        fairy: 2,
    },
    fairy: {
        normal: 1,
        fire: 0.5,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 2,
        poison: 0.5,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 2,
        steel: 0.5,
        fairy: 1,
    },
};

module.exports = {
    testcases: [
        // Public test cases (first 3)
        {
            input: [
                { name: 'Flamethrower', type: 'fire' },
                { name: 'Bulbasaur', type: ['grass'], level: 10 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: true,
            description: 'Fire move against Grass defender should be super effective',
        },
        {
            input: [{ name: 'Water Gun', type: 'water' }, { name: 'Bulbasaur', type: ['grass'], level: 10 }, typeChart],
            expected: "It's not very effective...",
            isPublic: true,
            description: 'Water move against Grass defender should be not very effective',
        },
        {
            input: [{ name: 'Tackle', type: 'normal' }, { name: 'Pidgey', type: ['flying'], level: 5 }, typeChart],
            expected: 'Normal',
            isPublic: true,
            description: 'Normal move against Flying defender should be neutral',
        },
        // Private test cases
        {
            input: [
                { name: 'Flamethrower', type: 'fire' },
                { name: 'Ogerpon', type: ['grass', 'rock'], level: 40 },
                typeChart,
            ],
            expected: 'Normal',
            isPublic: false,
            description: 'Fire against Grass/Rock dual-type (2x * 0.5x = 1x)',
        },
        {
            input: [
                { name: 'Thunderbolt', type: 'electric' },
                { name: 'Gyarados', type: ['water', 'flying'], level: 30 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Electric against Water/Flying dual-type (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Ice Beam', type: 'ice' },
                { name: 'Dragonite', type: ['dragon', 'flying'], level: 50 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Ice against Dragon/Flying dual-type (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Earthquake', type: 'ground' },
                { name: 'Pikachu', type: ['electric'], level: 25 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Ground move against Electric defender should be super effective (2x)',
        },
        {
            input: [
                { name: 'Shadow Ball', type: 'ghost' },
                { name: 'Alakazam', type: ['psychic'], level: 45 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Ghost move against Psychic defender (2x)',
        },
        {
            input: [
                { name: 'Karate Chop', type: 'fighting' },
                { name: 'Gengar', type: ['ghost', 'poison'], level: 35 },
                typeChart,
            ],
            expected: "It's not very effective...",
            isPublic: false,
            description: 'Fighting against Ghost/Poison dual-type (0x * 0.5x = 0x)',
        },
        {
            input: [
                { name: 'Dragon Claw', type: 'dragon' },
                { name: 'Salamence', type: ['dragon', 'flying'], level: 55 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Dragon against Dragon/Flying dual-type (2x * 1x = 2x)',
        },
        {
            input: [
                { name: 'Psychic', type: 'psychic' },
                { name: 'Machamp', type: ['fighting'], level: 40 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Psychic move against Fighting defender (2x)',
        },
        {
            input: [
                { name: 'Rock Slide', type: 'rock' },
                { name: 'Charizard', type: ['fire', 'flying'], level: 36 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Rock against Fire/Flying dual-type (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Poison Jab', type: 'poison' },
                { name: 'Steelix', type: ['steel', 'ground'], level: 42 },
                typeChart,
            ],
            expected: "It's not very effective...",
            isPublic: false,
            description: 'Poison against Steel/Ground dual-type (0x * 0.5x = 0x)',
        },
        {
            input: [
                { name: 'Moonblast', type: 'fairy' },
                { name: 'Hydreigon', type: ['dark', 'dragon'], level: 60 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Fairy against Dark/Dragon dual-type (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Steel Wing', type: 'steel' },
                { name: 'Tyranitar', type: ['rock', 'dark'], level: 55 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Steel against Rock/Dark dual-type (2x * 1x = 2x)',
        },
        {
            input: [
                { name: 'Bug Buzz', type: 'bug' },
                { name: 'Meowscarada', type: ['grass', 'dark'], level: 36 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Bug against Grass/Dark dual-type (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Flare Blitz', type: 'fire' },
                { name: 'Scizor', type: ['bug', 'steel'], level: 50 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Fire against Bug/Steel (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Surf', type: 'water' },
                { name: 'Rhyhorn', type: ['ground', 'rock'], level: 28 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Water against Ground/Rock dual-type (2x * 2x = 4x)',
        },
        {
            input: [
                { name: 'Dark Pulse', type: 'dark' },
                { name: 'Gengar', type: ['ghost', 'poison'], level: 38 },
                typeChart,
            ],
            expected: "It's super effective!",
            isPublic: false,
            description: 'Dark against Ghost/Poison dual-type (2x * 1x = 2x)',
        },
        {
            input: [
                { name: 'Quick Attack', type: 'normal' },
                { name: 'Lucario', type: ['fighting', 'steel'], level: 40 },
                typeChart,
            ],
            expected: "It's not very effective...",
            isPublic: false,
            description: 'Normal against Fighting/Steel dual-type (1x * 0.5x = 0.5x)',
        },
    ],
};
