module.exports = {
    testcases: [
        {
            input: [{ name: 'Alice', age: 30 }],
            expected: 30,
            isPublic: true,
            description: 'Returns age 30 from a standard person object',
        },
        {
            input: [{ age: 0 }],
            expected: 0,
            isPublic: true,
            description: 'Returns 0 when age is zero',
        },
        {
            input: [{ name: 'Bob', age: 45, city: 'SG' }],
            expected: 45,
            isPublic: true,
            description: 'Returns age correctly even with extra properties',
        },
        {
            input: [{ name: 'Cara', age: 18 }],
            expected: 18,
            isPublic: false,
            description: 'Returns a typical teen age value',
        },
        {
            input: [{ name: 'Dylan', age: 5 }],
            expected: 5,
            isPublic: false,
            description: 'Returns single-digit age correctly',
        },
        {
            input: [{ name: 'Eve', age: 21 }],
            expected: 21,
            isPublic: false,
            description: 'Returns young adult age correctly',
        },
        {
            input: [{ name: 'Fay', age: 30 }],
            expected: 30,
            isPublic: false,
            description: 'Returns numeric age from string-like scenario',
        },
        {
            input: [{ name: 'Gus', age: 8 }],
            expected: 8,
            isPublic: false,
            description: 'Returns child age correctly',
        },
        {
            input: [{ name: 'Hui', age: 12 }],
            expected: 12,
            isPublic: false,
            description: 'Returns pre-teen age correctly',
        },
        {
            input: [{ name: 'Ian', age: 14 }],
            expected: 14,
            isPublic: false,
            description: 'Returns teen age correctly',
        },
        {
            input: [{ name: 'Jen', age: 25 }],
            expected: 25,
            isPublic: false,
            description: 'Returns mid-20s age correctly',
        },
        {
            input: [{ name: 'Kai', age: 26 }],
            expected: 26,
            isPublic: false,
            description: 'Returns nearby adult age correctly',
        },
        {
            input: [{ name: 'Lia', age: 27 }],
            expected: 27,
            isPublic: false,
            description: 'Returns age when property is explicitly present',
        },
        {
            input: [{ age: 99, name: 'Moe' }],
            expected: 99,
            isPublic: false,
            description: 'Works regardless of property declaration order',
        },
        {
            input: [{ age: 1 }],
            expected: 1,
            isPublic: false,
            description: 'Returns small positive integer age',
        },
        {
            input: [{ age: 120, retired: true }],
            expected: 120,
            isPublic: false,
            description: 'Returns large realistic age values',
        },
        {
            input: [{ age: 110 }],
            expected: 110,
            isPublic: false,
            description: 'Returns three-digit age values correctly',
        },
        {
            input: [{ name: 'Nia', age: 67 }],
            expected: 67,
            isPublic: false,
            description: 'Returns senior age correctly',
        },
        {
            input: [{ name: 'Omar', age: 64, AGE: 50 }],
            expected: 64,
            isPublic: false,
            description: 'Uses lowercase age key when similar keys exist',
        },
        {
            input: [{ age: 32, name: 'Pia', city: 'Singapore' }],
            expected: 32,
            isPublic: false,
            description: 'Returns age correctly with extra unrelated fields',
        },
    ],
};
