module.exports = {
    testcases: [
        { input: [100, 20, 15], expected: 25, isPublic: true, description: 'Sample case: final balance should be 25' },
        { input: [50, 10, 12], expected: 14, isPublic: true, description: 'Sample case: final balance should be 14' },
        { input: [80, 30, 20], expected: 40, isPublic: true, description: 'Sample case: final balance should be 40' },
        { input: [20, 20, 5], expected: 20, isPublic: false, description: 'Already at target balance; no withdrawal' },
        {
            input: [19, 20, 5],
            expected: 19,
            isPublic: false,
            description: 'Starting below target should remain unchanged',
        },
        {
            input: [30, 10, 25],
            expected: 30,
            isPublic: false,
            description: 'Single withdrawal would drop below target',
        },
        { input: [30, 10, 20], expected: 10, isPublic: false, description: 'Withdrawal lands exactly at target' },
        {
            input: [31, 10, 20],
            expected: 11,
            isPublic: false,
            description: 'One withdrawal allowed, second not allowed',
        },
        {
            input: [100, 0, 30],
            expected: 10,
            isPublic: false,
            description: 'Withdraw repeatedly until next would go negative',
        },
        {
            input: [100, 1, 33],
            expected: 1,
            isPublic: false,
            description: 'Can reach target exactly by repeated withdrawals',
        },
        { input: [5, 0, 10], expected: 5, isPublic: false, description: 'Withdrawal too large for first step' },
        { input: [50, 49, 1], expected: 49, isPublic: false, description: 'Only one withdrawal to reach target' },
        {
            input: [50, 49, 2],
            expected: 50,
            isPublic: false,
            description: 'No withdrawal possible without dropping below target',
        },
        { input: [0, 0, 1], expected: 0, isPublic: false, description: 'Zero balance with zero target stays zero' },
        {
            input: [0, -10, 3],
            expected: -9,
            isPublic: false,
            description: 'Can continue into negatives while respecting target bound',
        },
        {
            input: [10, 10, 0],
            expected: 10,
            isPublic: false,
            description: 'Zero withdrawal amount should return starting balance',
        },
        {
            input: [10, 5, -1],
            expected: 10,
            isPublic: false,
            description: 'Negative withdrawal amount should return starting balance',
        },
        {
            input: [100, 50, 25],
            expected: 50,
            isPublic: false,
            description: 'Multiple withdrawals ending exactly at target',
        },
        { input: [99, 50, 25], expected: 74, isPublic: false, description: 'One valid withdrawal, second invalid' },
        {
            input: [75, 31, 15],
            expected: 45,
            isPublic: false,
            description: 'Stops before crossing non-divisible target boundary',
        },
    ],
};
