module.exports = {
    testcases: [
        {
            input: [1],
            expected: 6,
            isPublic: true,
            description: 'Secret 1 should take 6 guesses with midpoint strategy',
        },
        {
            input: [100],
            expected: 7,
            isPublic: true,
            description: 'Secret 100 takes 7 guesses with standard bounded midpoint updates',
        },
        { input: [50], expected: 1, isPublic: true, description: 'Secret 50 is found immediately' },
        { input: [75], expected: 2, isPublic: false, description: '50 then 75' },
        { input: [25], expected: 2, isPublic: false, description: '50 then 25' },
        { input: [63], expected: 6, isPublic: false, description: 'Secret 63 requires 6 guesses' },
        { input: [62], expected: 3, isPublic: false, description: '50, 75, 62' },
        { input: [74], expected: 7, isPublic: false, description: 'Secret 74 takes 7 guesses' },
        { input: [76], expected: 6, isPublic: false, description: 'Secret 76 takes 6 guesses' },
        { input: [99], expected: 6, isPublic: false, description: 'Secret 99 takes 6 guesses' },
        { input: [2], expected: 7, isPublic: false, description: 'Secret 2 takes 7 guesses' },
        { input: [3], expected: 5, isPublic: false, description: 'Secret 3 takes 5 guesses' },
        { input: [4], expected: 6, isPublic: false, description: 'Secret 4 takes 6 guesses' },
        { input: [5], expected: 7, isPublic: false, description: 'Secret 5 takes 7 guesses' },
        { input: [49], expected: 7, isPublic: false, description: 'Secret 49 takes 7 guesses' },
        { input: [51], expected: 6, isPublic: false, description: 'Secret 51 takes 6 guesses' },
        { input: [52], expected: 7, isPublic: false, description: 'Secret 52 takes 7 guesses' },
        { input: [88], expected: 3, isPublic: false, description: '50, 75, 88' },
        { input: [94], expected: 4, isPublic: false, description: '50, 75, 88, 94' },
        { input: [97], expected: 5, isPublic: false, description: '50, 75, 88, 94, 97' },
    ],
};
