module.exports = {
    testcases: [
        // Public test cases (first 3)
        {
            input: [[10, 20, 30]],
            commands: [
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 10, options: {} },
                { value: 20, options: {} },
                { value: 30, options: {} },
                { value: 10, options: {} },
                { value: 20, options: {} },
                { value: undefined, options: {} },
                { value: 10, options: {} },
                { value: 20, options: {} },
            ],
            isPublic: true,
            description: 'Basic sequence: current, next through array, loop back, reset',
        },
        {
            input: [[5, 15, 25]],
            commands: [
                { method: 'current', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 5, options: {} },
                { value: 5, options: {} },
                { value: 15, options: {} },
                { value: 15, options: {} },
            ],
            isPublic: true,
            description: 'Multiple current() calls without advancing',
        },
        {
            input: [[100, 200]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 200, options: {} },
                { value: 100, options: {} },
                { value: 100, options: {} },
                { value: undefined, options: {} },
                { value: 100, options: {} },
            ],
            isPublic: true,
            description: 'Two element array: loop and reset behavior',
        },
        // Hidden test cases
        {
            input: [[42]],
            commands: [
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 42, options: {} },
                { value: 42, options: {} },
                { value: 42, options: {} },
                { value: 42, options: {} },
            ],
            isPublic: false,
            description: 'Single element: always returns same value',
        },
        {
            input: [[1, 2, 3, 4, 5]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 5, options: {} },
                { value: 1, options: {} },
                { value: 1, options: {} },
            ],
            isPublic: false,
            description: 'Five elements: loop back after reaching end',
        },
        {
            input: [[7, 14, 21, 28]],
            commands: [
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: undefined, options: {} },
                { value: 7, options: {} },
                { value: undefined, options: {} },
                { value: 7, options: {} },
            ],
            isPublic: false,
            description: 'Multiple resets without advancing',
        },
        {
            input: [[10, 20]],
            commands: [
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 20, options: {} },
                { value: undefined, options: {} },
                { value: 20, options: {} },
                { value: undefined, options: {} },
                { value: 10, options: {} },
            ],
            isPublic: false,
            description: 'Reset after advancing',
        },
        {
            input: [[3, 6, 9, 12, 15, 18]],
            commands: [
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 3, options: {} },
                { value: 6, options: {} },
                { value: 9, options: {} },
                { value: 12, options: {} },
            ],
            isPublic: false,
            description: 'Six elements: sequential access',
        },
        {
            input: [[50]],
            commands: [
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 50, options: {} },
                { value: undefined, options: {} },
                { value: 50, options: {} },
                { value: 50, options: {} },
            ],
            isPublic: false,
            description: 'Single element with reset',
        },
        {
            input: [[1, 2, 3]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 1, options: {} },
                { value: undefined, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
            ],
            isPublic: false,
            description: 'Three elements: full cycle then reset',
        },
        {
            input: [[11, 22, 33, 44]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 22, options: {} },
                { value: 33, options: {} },
                { value: 33, options: {} },
                { value: 44, options: {} },
                { value: 11, options: {} },
                { value: 11, options: {} },
            ],
            isPublic: false,
            description: 'Four elements: mix of next and current',
        },
        {
            input: [[99, 88, 77]],
            commands: [
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 99, options: {} },
                { value: 88, options: {} },
                { value: 77, options: {} },
                { value: 99, options: {} },
                { value: 99, options: {} },
            ],
            isPublic: false,
            description: 'Descending sequence: loop behavior',
        },
        {
            input: [[0, 1, 2, 3]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: undefined, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
            ],
            isPublic: false,
            description: 'Reset in middle of sequence',
        },
        {
            input: [[5, 10, 15, 20, 25, 30, 35]],
            commands: [
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 5, options: {} },
                { value: 10, options: {} },
                { value: 15, options: {} },
                { value: 20, options: {} },
                { value: 25, options: {} },
                { value: 30, options: {} },
            ],
            isPublic: false,
            description: 'Seven elements: partial traversal',
        },
        {
            input: [[100, 200, 300, 400]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 200, options: {} },
                { value: 300, options: {} },
                { value: 400, options: {} },
                { value: 100, options: {} },
                { value: 200, options: {} },
                { value: undefined, options: {} },
                { value: 100, options: {} },
            ],
            isPublic: false,
            description: 'Full loop plus extra, then reset',
        },
        {
            input: [[2, 4, 6]],
            commands: [
                { method: 'current', params: [] },
                { method: 'current', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 2, options: {} },
                { value: 2, options: {} },
                { value: 2, options: {} },
                { value: 4, options: {} },
            ],
            isPublic: false,
            description: 'Multiple current calls before next',
        },
        {
            input: [[8, 16]],
            commands: [
                { method: 'reset', params: [] },
                { method: 'reset', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: undefined, options: {} },
                { value: undefined, options: {} },
                { value: 16, options: {} },
                { value: 8, options: {} },
                { value: undefined, options: {} },
                { value: 16, options: {} },
            ],
            isPublic: false,
            description: 'Multiple resets and loops',
        },
        {
            input: [[1, 3, 5, 7, 9]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 3, options: {} },
                { value: 5, options: {} },
                { value: 7, options: {} },
                { value: 9, options: {} },
                { value: 1, options: {} },
                { value: 3, options: {} },
                { value: 3, options: {} },
            ],
            isPublic: false,
            description: 'Complete loop and continue',
        },
        {
            input: [[25, 50, 75, 100]],
            commands: [
                { method: 'current', params: [] },
                { method: 'reset', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'reset', params: [] },
                { method: 'next', params: [] },
            ],
            expected: [
                { value: 25, options: {} },
                { value: undefined, options: {} },
                { value: 25, options: {} },
                { value: 50, options: {} },
                { value: undefined, options: {} },
                { value: 50, options: {} },
            ],
            isPublic: false,
            description: 'Reset at various positions',
        },
        {
            input: [[10, 20, 30, 40, 50]],
            commands: [
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'next', params: [] },
                { method: 'current', params: [] },
            ],
            expected: [
                { value: 20, options: {} },
                { value: 30, options: {} },
                { value: 40, options: {} },
                { value: 40, options: {} },
                { value: 50, options: {} },
                { value: 10, options: {} },
                { value: 20, options: {} },
                { value: 20, options: {} },
            ],
            isPublic: false,
            description: 'Five elements: multiple cycles with current checks',
        },
    ],
    options: {
        type: 'commands',
    },
};
