module.exports = {
    testcases: [
        { input: ['hello'], expected: 'olleh', isPublic: true, description: 'Reverse hello' },
        { input: ['world'], expected: 'dlrow', isPublic: true, description: 'Reverse world' },
        { input: ['a'], expected: 'a', isPublic: true, description: 'Single character remains same' },
        { input: [''], expected: '', isPublic: false, description: 'Empty string remains empty' },
        { input: ['ab'], expected: 'ba', isPublic: false, description: 'Two-character reversal' },
        {
            input: ['racecar'],
            expected: 'racecar',
            isPublic: false,
            description: 'Palindrome stays same when reversed',
        },
        { input: ['12345'], expected: '54321', isPublic: false, description: 'Numeric characters reverse correctly' },
        { input: ['A B'], expected: 'B A', isPublic: false, description: 'Spaces are preserved in reverse order' },
        { input: ['JavaScript'], expected: 'tpircSavaJ', isPublic: false, description: 'Mixed case reversal' },
        { input: ['  lead'], expected: 'dael  ', isPublic: false, description: 'Leading spaces become trailing' },
        { input: ['trail  '], expected: '  liart', isPublic: false, description: 'Trailing spaces become leading' },
        { input: ['!@#$'], expected: '$#@!', isPublic: false, description: 'Special characters reverse correctly' },
        { input: ['abc def'], expected: 'fed cba', isPublic: false, description: 'Internal space preserved' },
        { input: ['UPPER'], expected: 'REPPU', isPublic: false, description: 'All uppercase reversed' },
        { input: ['lower'], expected: 'rewol', isPublic: false, description: 'All lowercase reversed' },
        { input: ['MiXeD123'], expected: '321DeXiM', isPublic: false, description: 'Alphanumeric mixed case reversal' },
        { input: ['0 1 2'], expected: '2 1 0', isPublic: false, description: 'Digits and spaces reverse' },
        { input: ['noon'], expected: 'noon', isPublic: false, description: 'Even-length palindrome' },
        { input: ['xyz '], expected: ' zyx', isPublic: false, description: 'Ending space moves to start' },
        { input: [' reverse '], expected: ' esrever ', isPublic: false, description: 'Surrounding spaces preserved' },
    ],
};
