module.exports = {
    testcases: [
        // Public test cases (first 3)
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: [1, 2], options: { type: 'JSON' } },
            ],
            isPublic: true,
            description: 'Take two numbers: should return 1, then 2, queue should be [1, 2]',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 1, options: {} },
                { value: [2], options: { type: 'JSON' } },
            ],
            isPublic: true,
            description: 'Take 2, serve 1: queue should be [2]',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: [2], options: { type: 'JSON' } },
            ],
            isPublic: true,
            description: 'Take 1, serve, take another: queue should be [2]',
        },
        // Hidden test cases
        {
            input: [],
            commands: [{ method: 'getCurrentQueue', params: [] }],
            expected: [{ value: [], options: { type: 'JSON' } }],
            isPublic: false,
            description: 'Empty queue initially',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: [1], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Single customer in queue',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: [1, 2, 3], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Three customers in queue: [1, 2, 3]',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: [3], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'FIFO order: serve 1, then 2, leaving [3]',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 1, options: {} },
                { value: [], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Serve all customers: queue becomes empty',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 1, options: {} },
                { value: 3, options: {} },
                { value: [2, 3], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Mixed operations: [2, 3] in queue',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 5, options: {} },
                { value: [1, 2, 3, 4, 5], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Five customers: [1, 2, 3, 4, 5]',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: [], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Serve all three customers: queue empty',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: [3], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Alternating take and serve: [3] remains',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 1, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 2, options: {} },
                { value: [3, 4], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Complex sequence: [3, 4] in queue',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: [3, 4], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Add 4, serve 2: [3, 4] remains',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 5, options: {} },
                { value: 1, options: {} },
                { value: [2, 3, 4, 5], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Add 5, serve 1: [2, 3, 4, 5] remains',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 3, options: {} },
                { value: [], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Take-serve pattern: all served, empty queue',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 5, options: {} },
                { value: 6, options: {} },
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: [4, 5, 6], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Six customers, serve three: [4, 5, 6]',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: [1, 2], options: { type: 'JSON' } },
                { value: 1, options: {} },
                { value: [2], options: { type: 'JSON' } },
                { value: 2, options: {} },
                { value: [], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Check queue state between operations',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 1, options: {} },
                { value: 4, options: {} },
                { value: 5, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: [4, 5], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Complex flow: [4, 5] remains',
        },
        {
            input: [],
            commands: [
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'serveNextCustomer', params: [] },
                { method: 'takeANumber', params: [] },
                { method: 'getCurrentQueue', params: [] },
            ],
            expected: [
                { value: 1, options: {} },
                { value: 2, options: {} },
                { value: 3, options: {} },
                { value: 4, options: {} },
                { value: 1, options: {} },
                { value: 5, options: {} },
                { value: 2, options: {} },
                { value: 6, options: {} },
                { value: [3, 4, 5, 6], options: { type: 'JSON' } },
            ],
            isPublic: false,
            description: 'Interleaved operations: [3, 4, 5, 6] remains',
        },
    ],
    options: {
        type: 'commands',
    },
};
