module.exports = {
    testcases: [
        { input: [48, 18], expected: 6, isPublic: true, description: 'Sample: gcd(48, 18) is 6' },
        {
            input: [98, 56],
            expected: 14,
            isPublic: true,
            description: 'Sample reordered to satisfy a > b: gcd(98, 56) is 14',
        },
        { input: [101, 10], expected: 1, isPublic: true, description: 'Sample: gcd(101, 10) is 1' },
        { input: [12, 8], expected: 4, isPublic: false, description: 'gcd(12, 8) is 4' },
        { input: [13, 7], expected: 1, isPublic: false, description: 'Two primes are coprime with a > b' },
        { input: [100, 25], expected: 25, isPublic: false, description: 'One multiple of the other' },
        { input: [81, 27], expected: 27, isPublic: false, description: 'Exact divisor case' },
        { input: [270, 192], expected: 6, isPublic: false, description: 'Classic Euclid example' },
        { input: [999, 1], expected: 1, isPublic: false, description: 'gcd with 1 is always 1 and satisfies a > b' },
        { input: [2, 1], expected: 1, isPublic: false, description: 'Smallest strict positive a > b case' },
        { input: [25, 24], expected: 1, isPublic: false, description: 'Consecutive numbers are coprime' },
        { input: [64, 32], expected: 32, isPublic: false, description: 'Power-of-two multiple case' },
        { input: [84, 36], expected: 12, isPublic: false, description: 'Common factor greater than 1' },
        { input: [1071, 462], expected: 21, isPublic: false, description: 'Another Euclid example with a > b' },
        { input: [123456, 7890], expected: 6, isPublic: false, description: 'Large values gcd computed correctly' },
        { input: [391, 299], expected: 23, isPublic: false, description: 'Composite numbers with gcd 23' },
        { input: [144, 96], expected: 48, isPublic: false, description: 'Both divisible by 48' },
        { input: [65, 40], expected: 5, isPublic: false, description: 'Mixed factors with gcd 5' },
        { input: [121, 11], expected: 11, isPublic: false, description: 'Square number and root' },
        { input: [500, 125], expected: 125, isPublic: false, description: 'Exact quarter multiple case' },
    ],
};
