module.exports = {
    testcases: [
        // Public test cases (first 3)
        {
            input: [
                'electric',
                ['water', 'flying'],
                {
                    electric: { water: 2, flying: 2 },
                },
            ],
            expected: 4,
            isPublic: true,
            description: 'Electric vs Water/Flying: 2 * 2 = 4',
        },
        {
            input: [
                'fire',
                ['grass', 'rock'],
                {
                    fire: { grass: 2, rock: 0.5 },
                },
            ],
            expected: 1,
            isPublic: true,
            description: 'Fire vs Grass/Rock: 2 * 0.5 = 1',
        },
        {
            input: [
                'fighting',
                ['normal', 'ghost'],
                {
                    fighting: { normal: 2, ghost: 0 },
                },
            ],
            expected: 0,
            isPublic: true,
            description: 'Fighting vs Normal/Ghost: 2 * 0 = 0',
        },
        // Hidden test cases
        {
            input: [
                'water',
                ['fire', 'ground'],
                {
                    water: { fire: 2, ground: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Water vs Fire/Ground: 2 * 2 = 4',
        },
        {
            input: [
                'grass',
                ['water', 'rock'],
                {
                    grass: { water: 2, rock: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Grass vs Water/Rock: 2 * 2 = 4',
        },
        {
            input: [
                'fire',
                ['grass', 'ice'],
                {
                    fire: { grass: 2, ice: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Fire vs Grass/Ice: 2 * 2 = 4',
        },
        {
            input: [
                'electric',
                ['water'],
                {
                    electric: { water: 2 },
                },
            ],
            expected: 2,
            isPublic: false,
            description: 'Electric vs Water: 2 = 2',
        },
        {
            input: [
                'fighting',
                ['normal'],
                {
                    fighting: { normal: 2 },
                },
            ],
            expected: 2,
            isPublic: false,
            description: 'Fighting vs Normal: 2 = 2',
        },
        {
            input: [
                'water',
                ['grass'],
                {
                    water: { grass: 0.5 },
                },
            ],
            expected: 0.5,
            isPublic: false,
            description: 'Water vs Grass: 0.5 = 0.5',
        },
        {
            input: [
                'fire',
                ['water', 'rock'],
                {
                    fire: { water: 0.5, rock: 0.5 },
                },
            ],
            expected: 0.25,
            isPublic: false,
            description: 'Fire vs Water/Rock: 0.5 * 0.5 = 0.25',
        },
        {
            input: [
                'electric',
                ['grass', 'electric'],
                {
                    electric: { grass: 0.5, electric: 0.5 },
                },
            ],
            expected: 0.25,
            isPublic: false,
            description: 'Electric vs Grass/Electric: 0.5 * 0.5 = 0.25',
        },
        {
            input: [
                'normal',
                ['rock', 'steel'],
                {
                    normal: { rock: 0.5, steel: 0.5 },
                },
            ],
            expected: 0.25,
            isPublic: false,
            description: 'Normal vs Rock/Steel: 0.5 * 0.5 = 0.25',
        },
        {
            input: [
                'grass',
                ['fire', 'poison'],
                {
                    grass: { fire: 0.5, poison: 0.5 },
                },
            ],
            expected: 0.25,
            isPublic: false,
            description: 'Grass vs Fire/Poison: 0.5 * 0.5 = 0.25',
        },
        {
            input: [
                'psychic',
                ['fighting'],
                {
                    psychic: { fighting: 2 },
                },
            ],
            expected: 2,
            isPublic: false,
            description: 'Psychic vs Fighting: 2 = 2',
        },
        {
            input: [
                'ground',
                ['electric', 'fire'],
                {
                    ground: { electric: 2, fire: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Ground vs Electric/Fire: 2 * 2 = 4',
        },
        {
            input: [
                'flying',
                ['grass', 'fighting'],
                {
                    flying: { grass: 2, fighting: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Flying vs Grass/Fighting: 2 * 2 = 4',
        },
        {
            input: [
                'ice',
                ['grass', 'dragon'],
                {
                    ice: { grass: 2, dragon: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Ice vs Grass/Dragon: 2 * 2 = 4',
        },
        {
            input: [
                'bug',
                ['grass', 'psychic'],
                {
                    bug: { grass: 2, psychic: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Bug vs Grass/Psychic: 2 * 2 = 4',
        },
        {
            input: [
                'rock',
                ['fire', 'flying'],
                {
                    rock: { fire: 2, flying: 2 },
                },
            ],
            expected: 4,
            isPublic: false,
            description: 'Rock vs Fire/Flying: 2 * 2 = 4',
        },
        {
            input: [
                'steel',
                ['ice'],
                {
                    steel: { ice: 2 },
                },
            ],
            expected: 2,
            isPublic: false,
            description: 'Steel vs Ice: 2 = 2',
        },
    ],
};

const typeChart = {
    normal: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 0.5,
        ghost: 0,
        dragon: 1,
        dark: 1,
        steel: 0.5,
    },
    fire: {
        normal: 1,
        fire: 0.5,
        water: 0.5,
        electric: 1,
        grass: 2,
        ice: 2,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 2,
        rock: 0.5,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 2,
    },
    water: {
        normal: 1,
        fire: 2,
        water: 0.5,
        electric: 1,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 2,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 2,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 1,
    },
    electric: {
        normal: 1,
        fire: 1,
        water: 2,
        electric: 0.5,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 0,
        flying: 2,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 1,
    },
    grass: {
        normal: 1,
        fire: 0.5,
        water: 2,
        electric: 1,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 0.5,
        ground: 2,
        flying: 0.5,
        psychic: 1,
        bug: 0.5,
        rock: 2,
        ghost: 1,
        dragon: 0.5,
        dark: 1,
        steel: 0.5,
    },
    ice: {
        normal: 1,
        fire: 0.5,
        water: 0.5,
        electric: 1,
        grass: 2,
        ice: 0.5,
        fighting: 1,
        poison: 1,
        ground: 2,
        flying: 2,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 1,
        steel: 0.5,
    },
    fighting: {
        normal: 2,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 2,
        fighting: 1,
        poison: 0.5,
        ground: 1,
        flying: 0.5,
        psychic: 0.5,
        bug: 0.5,
        rock: 2,
        ghost: 0,
        dragon: 1,
        dark: 2,
        steel: 2,
    },
    poison: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 2,
        ice: 1,
        fighting: 1,
        poison: 0.5,
        ground: 0.5,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 0.5,
        ghost: 0.5,
        dragon: 1,
        dark: 1,
        steel: 0,
    },
    ground: {
        normal: 1,
        fire: 2,
        water: 1,
        electric: 2,
        grass: 0.5,
        ice: 1,
        fighting: 1,
        poison: 2,
        ground: 1,
        flying: 0,
        psychic: 1,
        bug: 0.5,
        rock: 2,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 2,
    },
    flying: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 0.5,
        grass: 2,
        ice: 1,
        fighting: 2,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 2,
        rock: 0.5,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 0.5,
    },
    psychic: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 2,
        poison: 2,
        ground: 1,
        flying: 1,
        psychic: 0.5,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 1,
        dark: 0,
        steel: 0.5,
    },
    bug: {
        normal: 1,
        fire: 0.5,
        water: 1,
        electric: 1,
        grass: 2,
        ice: 1,
        fighting: 0.5,
        poison: 0.5,
        ground: 1,
        flying: 0.5,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 0.5,
        dragon: 1,
        dark: 2,
        steel: 0.5,
    },
    rock: {
        normal: 1,
        fire: 2,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 2,
        fighting: 0.5,
        poison: 1,
        ground: 0.5,
        flying: 2,
        psychic: 1,
        bug: 2,
        rock: 1,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 0.5,
    },
    ghost: {
        normal: 0,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 2,
        dragon: 1,
        dark: 0.5,
        steel: 0.5,
    },
    dragon: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 1,
        steel: 0.5,
    },
    dark: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 0.5,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 2,
        dragon: 1,
        dark: 0.5,
        steel: 0.5,
    },
    steel: {
        normal: 1,
        fire: 0.5,
        water: 0.5,
        electric: 0.5,
        grass: 1,
        ice: 2,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 2,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 0.5,
    },
};
