module.exports = {
    testcases: [
        {
            input: [{ name: 'Alice', age: 30 }],
            expected: 'Alice',
            isPublic: true,
            description: 'Reads a standard string name from person object',
        },
        {
            input: [{ name: 'Bob' }],
            expected: 'Bob',
            isPublic: true,
            description: 'Works when object has only the name property',
        },
        {
            input: [{ name: '' }],
            expected: '',
            isPublic: true,
            description: 'Returns empty string when name is empty string',
        },
        {
            input: [{ name: 'Charlie Brown', city: 'London' }],
            expected: 'Charlie Brown',
            isPublic: false,
            description: 'Returns full name with spaces correctly',
        },
        {
            input: [{ name: 'Eve-01', role: 'admin' }],
            expected: 'Eve-01',
            isPublic: false,
            description: 'Handles name containing punctuation',
        },
        {
            input: [{ name: '123' }],
            expected: '123',
            isPublic: false,
            description: 'Returns numeric-looking string unchanged',
        },
        {
            input: [{ name: '0', age: 40 }],
            expected: '0',
            isPublic: false,
            description: 'Returns string zero name correctly',
        },
        {
            input: [{ name: '-15' }],
            expected: '-15',
            isPublic: false,
            description: 'Returns signed numeric-looking string correctly',
        },
        {
            input: [{ name: 'FalseName' }],
            expected: 'FalseName',
            isPublic: false,
            description: 'Returns alphabetical string name correctly',
        },
        {
            input: [{ name: 'TrueName' }],
            expected: 'TrueName',
            isPublic: false,
            description: 'Returns another regular string name correctly',
        },
        {
            input: [{ name: 'null' }],
            expected: 'null',
            isPublic: false,
            description: 'Returns literal string null correctly',
        },
        {
            input: [{ name: 'undefined', age: 20 }],
            expected: 'undefined',
            isPublic: false,
            description: 'Returns literal string undefined correctly',
        },
        {
            input: [{ name: 'Nina_Ong', age: 20 }],
            expected: 'Nina_Ong',
            isPublic: false,
            description: 'Handles underscore in string name',
        },
        {
            input: [{ name: 'Dr. Tan' }],
            expected: 'Dr. Tan',
            isPublic: false,
            description: 'Handles period and space in string name',
        },
        {
            input: [{ name: '   ' }],
            expected: '   ',
            isPublic: false,
            description: 'Keeps whitespace-only names unchanged',
        },
        {
            input: [{ name: 'name', nickname: 'N' }],
            expected: 'name',
            isPublic: false,
            description: 'Returns exact name even with similarly named properties',
        },
        {
            input: [{ name: 'A'.repeat(20) }],
            expected: 'A'.repeat(20),
            isPublic: false,
            description: 'Handles long names correctly',
        },
        {
            input: [{ name: "O'Neil", age: 18 }],
            expected: "O'Neil",
            isPublic: false,
            description: 'Handles apostrophe in string names',
        },
        {
            input: [{ age: 99, name: 'LastProperty' }],
            expected: 'LastProperty',
            isPublic: false,
            description: 'Reads name regardless of property order',
        },
        {
            input: [{ name: 'CaseSensitive', Name: 'WrongKey' }],
            expected: 'CaseSensitive',
            isPublic: false,
            description: 'Uses exact lowercase key name',
        },
    ],
};
