module.exports = {
    testcases: [
        {
            input: [[-1, 0, 1, 2, 3]],
            expected: 3,
            isPublic: true,
            description: 'Counts positives in mixed array [-1, 0, 1, 2, 3] as 3',
        },
        {
            input: [[-5, -4, -3, -2, -1]],
            expected: 0,
            isPublic: true,
            description: 'All negative numbers should return 0',
        },
        {
            input: [[1, 2, 3, 4, 5]],
            expected: 5,
            isPublic: true,
            description: 'All positive numbers should return array length',
        },
        {
            input: [[]],
            expected: 0,
            isPublic: false,
            description: 'Empty array should return 0',
        },
        {
            input: [[0]],
            expected: 0,
            isPublic: false,
            description: 'Single zero is not positive',
        },
        {
            input: [[5]],
            expected: 1,
            isPublic: false,
            description: 'Single positive number should return 1',
        },
        {
            input: [[-5]],
            expected: 0,
            isPublic: false,
            description: 'Single negative number should return 0',
        },
        {
            input: [[0, 0, 0, 0]],
            expected: 0,
            isPublic: false,
            description: 'Array of zeros should return 0',
        },
        {
            input: [[-1, -2, -3, 4]],
            expected: 1,
            isPublic: false,
            description: 'Only one positive at the end',
        },
        {
            input: [[4, -1, -2, -3]],
            expected: 1,
            isPublic: false,
            description: 'Only one positive at the start',
        },
        {
            input: [[-2, 3, -4, 5, -6, 7]],
            expected: 3,
            isPublic: false,
            description: 'Alternating signs should count only positives',
        },
        {
            input: [[1, 0, -1, 2, 0, -2, 3]],
            expected: 3,
            isPublic: false,
            description: 'Zeros are excluded from positive count',
        },
        {
            input: [[100, 200, 300, -100, -200]],
            expected: 3,
            isPublic: false,
            description: 'Large positive values are counted correctly',
        },
        {
            input: [[-1000, 0, 1000]],
            expected: 1,
            isPublic: false,
            description: 'Mixed large negative, zero, and positive',
        },
        {
            input: [[0.1, -0.1, 2.5, 0, -3.2]],
            expected: 2,
            isPublic: false,
            description: 'Positive decimals should be counted',
        },
        {
            input: [[-0.5, -0.0001, 0.0001]],
            expected: 1,
            isPublic: false,
            description: 'Very small positive decimal should count',
        },
        {
            input: [[9, 8, 7, 6, 5, 4, 3, 2, 1]],
            expected: 9,
            isPublic: false,
            description: 'All positive descending numbers should return 9',
        },
        {
            input: [[-9, -8, -7, -6, -5, -4, -3, -2, -1]],
            expected: 0,
            isPublic: false,
            description: 'All negative descending numbers should return 0',
        },
        {
            input: [[1, -1, 1, -1, 1, -1, 1, -1]],
            expected: 4,
            isPublic: false,
            description: 'Repeated mixed signs should count four positives',
        },
        {
            input: [[-3, 0, 2, -1, 4, 0, 6, -8, 10]],
            expected: 4,
            isPublic: false,
            description: 'General mixed case with four positives',
        },
    ],
};
