module.exports = {
    testcases: [
        {
            input: [{ name: 'Alice', destination: 'Paris' }],
            expected: 'Welcome, Alice! Your booking to Paris is confirmed.',
            isPublic: true,
            description: 'Builds welcome message for Alice and Paris',
        },
        {
            input: [{ name: 'Bob', destination: 'New York' }],
            expected: 'Welcome, Bob! Your booking to New York is confirmed.',
            isPublic: true,
            description: 'Builds welcome message for Bob and New York',
        },
        {
            input: [{ name: 'Cara', destination: 'Tokyo' }],
            expected: 'Welcome, Cara! Your booking to Tokyo is confirmed.',
            isPublic: true,
            description: 'Builds welcome message for Cara and Tokyo',
        },
        {
            input: [{ name: 'David', destination: 'Singapore' }],
            expected: 'Welcome, David! Your booking to Singapore is confirmed.',
            isPublic: false,
            description: 'Handles a longer destination name correctly',
        },
        {
            input: [{ name: 'Eve', destination: 'Kuala Lumpur' }],
            expected: 'Welcome, Eve! Your booking to Kuala Lumpur is confirmed.',
            isPublic: false,
            description: 'Handles destination with space correctly',
        },
        {
            input: [{ name: 'Frank', destination: 'Los Angeles' }],
            expected: 'Welcome, Frank! Your booking to Los Angeles is confirmed.',
            isPublic: false,
            description: 'Handles two-word destination correctly',
        },
        {
            input: [{ name: 'Grace', destination: 'Rio-de-Janeiro' }],
            expected: 'Welcome, Grace! Your booking to Rio-de-Janeiro is confirmed.',
            isPublic: false,
            description: 'Handles hyphenated destination correctly',
        },
        {
            input: [{ name: 'Henry', destination: 'St. Louis' }],
            expected: 'Welcome, Henry! Your booking to St. Louis is confirmed.',
            isPublic: false,
            description: 'Handles destination with period punctuation',
        },
        {
            input: [{ name: 'Ivy', destination: 'Seoul' }],
            expected: 'Welcome, Ivy! Your booking to Seoul is confirmed.',
            isPublic: false,
            description: 'Handles short name and destination correctly',
        },
        {
            input: [{ name: 'Jack', destination: 'San Francisco' }],
            expected: 'Welcome, Jack! Your booking to San Francisco is confirmed.',
            isPublic: false,
            description: 'Handles destination with multiple words correctly',
        },
        {
            input: [{ name: 'Kate', destination: 'Cape Town' }],
            expected: 'Welcome, Kate! Your booking to Cape Town is confirmed.',
            isPublic: false,
            description: 'Builds message for mixed-case destination words',
        },
        {
            input: [{ name: 'Leo', destination: '123City' }],
            expected: 'Welcome, Leo! Your booking to 123City is confirmed.',
            isPublic: false,
            description: 'Supports destination strings containing numbers',
        },
        {
            input: [{ name: 'Mia', destination: 'Zone-5' }],
            expected: 'Welcome, Mia! Your booking to Zone-5 is confirmed.',
            isPublic: false,
            description: 'Supports destination strings with hyphen and number',
        },
        {
            input: [{ name: "O'Neil", destination: 'Dublin' }],
            expected: "Welcome, O'Neil! Your booking to Dublin is confirmed.",
            isPublic: false,
            description: 'Handles apostrophe in name correctly',
        },
        {
            input: [{ name: 'Quin', destination: "King's Cross" }],
            expected: "Welcome, Quin! Your booking to King's Cross is confirmed.",
            isPublic: false,
            description: 'Handles apostrophe in destination correctly',
        },
        {
            input: [{ name: 'Rae', destination: 'A' }],
            expected: 'Welcome, Rae! Your booking to A is confirmed.',
            isPublic: false,
            description: 'Handles single-character destination string',
        },
        {
            input: [{ name: 'Sam', destination: 'B2' }],
            expected: 'Welcome, Sam! Your booking to B2 is confirmed.',
            isPublic: false,
            description: 'Handles short alphanumeric destination string',
        },
        {
            input: [{ name: 'Tina', destination: 'North Pole' }],
            expected: 'Welcome, Tina! Your booking to North Pole is confirmed.',
            isPublic: false,
            description: 'Builds message for destination with compass word',
        },
        {
            input: [{ name: 'Uma', destination: 'South-End' }],
            expected: 'Welcome, Uma! Your booking to South-End is confirmed.',
            isPublic: false,
            description: 'Builds message for destination with hyphenated words',
        },
        {
            input: [{ name: 'Victor', destination: 'Central Station' }],
            expected: 'Welcome, Victor! Your booking to Central Station is confirmed.',
            isPublic: false,
            description: 'Builds message for longer name and destination',
        },
    ],
};
